db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
redis:
  image: redis
app:
  build: .
  command: "cd test/dummy && bundle exec rails s --port 3000 --binding 0.0.0.0"
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - redis
    - db
  environment:
    - RACK_ENV=development
worker:
  build: .
  command: bundle exec sidekiq
  links:
    - redis
  environment:
    - RACK_ENV=development
  volumes:
    - .:/myapp
