db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=mypassword
redis:
  image: redis
app:
  build: .
  command: "bundle exec rails s --port 3000 --binding 0.0.0.0"
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - redis
    - db
  environment:
    - RACK_ENV=development
worker:
  build: .
  command: bundle exec sidekiq
  links:
    - redis
    - db
  environment:
    - RACK_ENV=development
  volumes:
    - .:/myapp
